services:
  # ==== BACKEND ====
  - type: web
    name: kleveros-api
    env: node
    rootDir: server
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: PORT
        value: "3000"
    healthCheckPath: "/"
    autoDeploy: true

  # ==== FRONTEND ====
  - type: static_site
    name: kleveros-front
    rootDir: .
    buildCommand: ""
    staticPublishPath: "."
    autoDeploy: true